server.port: 7000

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/bookstoredb
      username: root
      password: Shabthana9	
  jpa:
    hibernate: 
      ddl-auto: update
    show:-ql: true
    defer_datasource_initialization: true
  
  sql:
    init:
      mode: always
 